#!/usr/bin/env python3
"""
Compile Runtime Presets from Fixture Contracts.
-----------------------------------------------
Reads `twin_config.yml` from all fixtures and generates `src/extractor/core/presets.py`.

Usage:
    python tools/tasks_loop/utils/compile_presets.py
"""
import sys
import yaml
import re
from pathlib import Path

# Constants (Globals to preserve)
COMPLEXITY_THRESHOLDS = {
    "table_count": 3,
    "multi_column": True,
    "page_count": 50,
    "has_math": True,
    "min_complexity": 2,
}

LLM_CONFIG = {
    "service": "marker.services.openai.OpenAIService",
    "api_key_env": "SCILLM_PROXY_KEY",
    "base_url": "http://localhost:4010",
    "model": "deepseek-ai/DeepSeek-V3",
}


def get_repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def compile_presets() -> bool:
    root = get_repo_root()
    fixtures_dir = root / "tools/tasks_loop/fixtures"
    target_file = root / "src/extractor/core/presets.py"

    print(f"Scanning fixtures in {fixtures_dir}...")

    registry = {}

    for path in fixtures_dir.glob("*/twin_config.yml"):
        try:
            with open(path, "r") as f:
                config = yaml.safe_load(f)

            preset_id = config.get("preset_id")
            runtime = config.get("runtime")

            if not preset_id or not runtime:
                # Not a runtime preset definition, just a test fixture
                continue

            print(f"  Found preset: {preset_id}")

            # Detection can be at top-level or inside runtime (for backward compat)
            detection = config.get("detection", {}) or runtime.get("detection", {})

            entry = {
                "category": config.get("category", "General"),
                "layout": config.get("layout", "single"),
                "errors": runtime.get("errors", []),
                "features": runtime.get("features", {}),
                "description": config.get("description", ""),
                "detection": detection,
            }

            # Validate regex pattern safety
            pat = entry["detection"].get("section_pattern")
            if pat:
                try:
                    re.compile(pat)
                except re.error as e:
                    print(f"  ERROR: Invalid regex in {preset_id}: {e}")
                    return False

            registry[preset_id] = entry

        except Exception as e:
            print(f"  Warning: Failed to process {path.name}: {e}")

    import pprint

    # Generate Python Code

    # helper for formatting
    def fmt(obj):
        return pprint.pformat(obj, indent=4, width=100)

    content = [
        '"""',
        "Extractor Calibration Presets & Detection Rules",
        "-----------------------------------------------",
        "AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
        "Source: tools/tasks_loop/fixtures/*/twin_config.yml",
        "Generated by: tools/tasks_loop/utils/compile_presets.py",
        '"""',
        "",
        f"PRESET_REGISTRY = {fmt(registry)}",
        "",
        "# Routing Thresholds for Fast vs Accurate Path",
        f"COMPLEXITY_THRESHOLDS = {fmt(COMPLEXITY_THRESHOLDS)}",
        "",
        "# LLM Service Configuration (for accurate mode)",
        f"LLM_CONFIG = {fmt(LLM_CONFIG)}",
        "",
    ]

    with open(target_file, "w") as f:
        f.write("\n".join(content))

    print(f"Successfully compiled {len(registry)} presets to {target_file}")
    return True


if __name__ == "__main__":
    if compile_presets():
        sys.exit(0)
    else:
        sys.exit(1)
