#!/usr/bin/env python3
"""
Simple debug script to understand the "INFER: 0" title issue.
"""

import os
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

def main():
    print("TITLE INFERENCE ISSUE - SIMPLE ANALYSIS")
    print("=" * 50)
    
    # Show current environment
    print(f"\nCurrent Environment:")
    chutes_vars = ["CHUTES_TEXT_MODEL", "CHUTES_API_BASE", "CHUTES_API_KEY", "STAGE05_LLM_INFER"]
    for var in chutes_vars:
        value = os.environ.get(var, "NOT SET")
        if value and len(value) > 20:
            value = value[:20] + "..."
        print(f"  {var}: {value}")
    
    # Test require_scillm_env
    from extractor.pipeline.utils.preflight import require_scillm_env
    
    print(f"\n1. Testing require_scillm_env():")
    ok, reason = require_scillm_env()
    print(f"   Result: ok={ok}, reason='{reason}'")
    
    if not ok:
        print(f"   ✗ This is why inference is failing!")
        print(f"   ✗ _chutes_title_infer_struct() will return None")
        print(f"   ✗ No 'INFER:' titles will be generated by 06a enricher")
    
    # Test the actual inference function
    print(f"\n2. Testing _chutes_title_infer_struct():")
    import importlib
    steps_module = importlib.import_module('extractor.pipeline.steps.06a_title_caption_enricher')
    
    sample_context = "Header: Parameter | Value | Unit\nSamples:\nTemperature | 25.0 | °C"
    result = steps_module._chutes_title_infer_struct(sample_context)
    print(f"   Result: {result}")
    
    if result is None:
        print(f"   ✗ Function returns None - no inference happening")
    else:
        print(f"   ✓ Function returned data: {result}")
    
    print(f"\n3. Where does 'INFER: 0' come from?")
    print(f"   - NOT from 06a title caption enricher!")
    print(f"   - This enricher sets title=None when env not set")
    print(f"   - Some OTHER part of pipeline adds 'INFER: 0'")
    print(f"   - Possible sources:")
    print(f"     * Stage 05 table extractor (if STAGE05_LLM_INFER='1')")
    print(f"     * Post-processing formatting")
    print(f"     * Display/UI code")
    print(f"     * Output rendering")
    
    print(f"\n4. Solution:")
    print(f"   - Set CHUTES_TEXT_MODEL in your environment")
    print(f"   - Check your .env file")
    print(f"   - Or find the actual source of 'INFER: 0' formatting")
    
    print(f"\n" + "=" * 50)
    print("ANALYSIS COMPLETE")

if __name__ == "__main__":
    main()