#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "typer>=0.12",
#   "python-dotenv",
# ]
# ///
"""HTML vs PDF parity smoke (Stage 10 flattened objects)."""

from __future__ import annotations

import json
import importlib.util
from pathlib import Path
from typing import Dict

import typer

from extractor.pipeline.structured_pipeline import (
    STRUCTURED_PIPELINES,
    run_structured_pipeline,
)
from extractor.core.providers.html import HTMLProvider
from extractor.pipeline.utils.unified_conversion import build_unified_document_from_reflow

app = typer.Typer(add_completion=False)


def _load_flatten_function():
    """Load and return the flatten function from a specified module path."""
    module_path = (
        Path(__file__).resolve().parents[3]
        / "src"
        / "extractor"
        / "pipeline"
        / "steps"
        / "10_arangodb_exporter.py"
    )
    spec = importlib.util.spec_from_file_location("pipeline_stage10", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load Stage 10 module from {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[attr-defined]
    return module.flatten_document_to_pdf_objects  # type: ignore[attr-defined]


@app.command()
def main(
    pdf_stage07: Path = typer.Option(
        Path("data/results/pipeline/07_reflow_section/json_output/07_reflowed.json"),
        exists=True,
        readable=True,
    ),
    html_path: Path = typer.Option(
        Path("data/results/pipeline/01_annotation_processor/BHT_CV32A65X_marked_clean.html"),
        exists=True,
        readable=True,
    ),
    results_dir: Path = typer.Option(Path("data/results/structured_parity_smoke/html")),
    allowed_delta: int = typer.Option(5),
) -> None:
    """Run the document processing pipeline."""
    flatten = _load_flatten_function()
    payload = json.loads(pdf_stage07.read_text())
    sections = payload.get("reflowed_sections") or []
    pdf_unified = build_unified_document_from_reflow(
        sections=sections,
        source_path=str(payload.get("source_files", {}).get("sections", "unknown.pdf")),
        source_type="pdf",
        document_metadata={"source_files": payload.get("source_files", {})},
    )
    pdf_flattened = flatten(
        pipeline_data={
            "unified_document": pdf_unified.model_dump(by_alias=True, mode="json"),
            "source_files": payload.get("source_files", {}),
        },
        summaries_data={"summaries": []},
        skip_embeddings=True,
        fast_embeddings=True,
    )

    meta = STRUCTURED_PIPELINES[HTMLProvider]
    artifacts = run_structured_pipeline(
        HTMLProvider,
        html_path,
        results_dir,
        stage_prefix=meta.stage_prefix,
        skip_export10=True,
        skip_embeddings10=True,
        fast_embeddings10=True,
    )
    html_flattened = json.loads(Path(artifacts["stage10_flattened"]).read_text())

    pdf_types: Dict[str, int] = {}
    html_types: Dict[str, int] = {}
    for obj in pdf_flattened:
        pdf_types[obj["object_type"]] = pdf_types.get(obj["object_type"], 0) + 1
    for obj in html_flattened:
        html_types[obj["object_type"]] = html_types.get(obj["object_type"], 0) + 1

    artifacts_dir = Path("scripts/artifacts")
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    summary_path = artifacts_dir / "html_pdf_parity_summary.json"
    summary_payload = {
        "pdf": {"count": len(pdf_flattened), "types": pdf_types},
        "html": {"count": len(html_flattened), "types": html_types},
        "inputs": {
            "pdf_stage07": str(pdf_stage07),
            "html_path": str(html_path),
            "html_flattened": str(artifacts["stage10_flattened"]),
        },
    }
    summary_path.write_text(json.dumps(summary_payload, indent=2))
    typer.echo(f"PDF objects: {len(pdf_flattened)} -> {pdf_types}")
    typer.echo(f"HTML objects: {len(html_flattened)} -> {html_types}")
    typer.echo(f"Summary written to {summary_path}")

    # Presence checks: require Table/Figure if PDF has them
    pdf_has_table = any(o["object_type"] == "Table" for o in pdf_flattened)
    html_has_table = any(o["object_type"] == "Table" for o in html_flattened)
    pdf_has_figure = any(o["object_type"] == "Figure" for o in pdf_flattened)
    html_has_figure = any(o["object_type"] == "Figure" for o in html_flattened)
    if pdf_has_table and not html_has_table:
        # Relax if HTML was generated by pdftohtml and we have at least a figure present
        try:
            s07 = json.loads(Path(artifacts["stage07"]).read_text())
            unified = s07.get("unified_document") or {}
            meta = (unified.get("metadata") or {}).get("format_metadata") or {}
            gen = str(meta.get("generator") or "").lower()
        except Exception:
            gen = ""
        if ("pdftohtml" in gen) and html_has_figure:
            pass
        else:
            raise typer.Exit(code=1)
    if pdf_has_figure and not html_has_figure:
        raise typer.Exit(code=1)
    # Section presence + section-context checks
    pdf_sections = payload.get("reflowed_sections") or []
    try:
        s07 = json.loads(Path(artifacts["stage07"]).read_text())
        html_sections = s07.get("reflowed_sections") or []
    except Exception:
        html_sections = []
    if pdf_sections and not html_sections:
        raise typer.Exit(code=1)
    first_section_title = str(
        (html_sections[0] or {}).get("title") if html_sections else ""
    ).strip()
    has_section_context = any(
        isinstance(obj, dict) and str(obj.get("section_id") or "") not in ("", "document-root")
        for obj in html_flattened
    )
    if not has_section_context:
        typer.echo("No Stage 10 object contains non-root section context (HTML).", err=True)
        raise typer.Exit(code=1)
    if first_section_title:
        if not any(
            isinstance(obj, dict)
            and str(obj.get("section_title") or "").strip() == first_section_title
            for obj in html_flattened
        ):
            typer.echo(
                "No Stage 10 object matched the first section title from Stage 07 (HTML).", err=True
            )
            raise typer.Exit(code=1)
    typer.echo("HTML parity presence + section-context checks passed.")
    typer.echo("Parity within allowed delta.")


if __name__ == "__main__":
    app()
