"""
Extractor Calibration Presets & Detection Rules
-----------------------------------------------
AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
Source: tools/tasks_loop/fixtures/*/twin_config.yml
Generated by: tools/tasks_loop/utils/compile_presets.py
"""

PRESET_REGISTRY = {   'arxiv': {   'category': 'Scientific',
                 'description': 'Academic papers (2-column, math, citations)',
                 'detection': {   'filename_triggers': ['arxiv', 'paper', 'journal', 'proceedings'],
                                  'keywords': [   'arXiv',
                                                  'Abstract',
                                                  'References',
                                                  'Introduction',
                                                  'Fig.'],
                                  'layout': 'double',
                                  'min_score': 2,
                                  'section_pattern': '^\\d+\\.\\s+[A-Z]'},
                 'errors': ['hyphenation', 'ligatures', 'split_tables', 'trapped_headers'],
                 'features': {   'enable_proving': True,
                                 'summarization_prompt': 'Analyze this section of a scientific '
                                                         'paper. Summarize the methodology, '
                                                         'results, and key claims.\n'
                                                         'Focus on the technical contribution.\n'},
                 'layout': 'double'},
    'requirements_spec': {   'category': 'Engineering',
                             'description': 'Requirements spec (Boeing/BHT style, nested lists)',
                             'detection': {   'filename_triggers': [   'spec',
                                                                       'requirement',
                                                                       'bht',
                                                                       'boeing',
                                                                       'std'],
                                              'keywords': [   'REQ-',
                                                              'Shall',
                                                              'Specification',
                                                              'Revision',
                                                              'Document Number'],
                                              'layout': 'single',
                                              'min_score': 2,
                                              'section_pattern': '^\\d+(\\.\\d+){2,}'},
                             'errors': [   'hyphenation',
                                           'ligatures',
                                           'trapped_headers',
                                           'nesting_complexity'],
                             'features': {   'enable_proving': True,
                                             'summarization_prompt': 'Analyze this section of a '
                                                                     'requirements specification. '
                                                                     'Summarize the key '
                                                                     'requirements, constraints, '
                                                                     'and verification criteria.\n'
                                                                     'Highlight any compliant or '
                                                                     'non-compliant states.\n'},
                             'layout': 'single'}}

# Routing Thresholds for Fast vs Accurate Path
COMPLEXITY_THRESHOLDS = {'has_math': True, 'min_complexity': 2, 'multi_column': True, 'page_count': 50, 'table_count': 3}

# LLM Service Configuration (for accurate mode)
LLM_CONFIG = {   'api_key_env': 'CHUTES_API_KEY',
    'base_url': 'https://llm.chutes.ai/v1',
    'model': 'deepseek-ai/DeepSeek-V3',
    'service': 'marker.services.openai.OpenAIService'}
